# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keksik5@yandex.ru",
  "avatar": "gift.jpg",
  "userName": "supercat1000",
  "password": "shining",
  "type": "обычный"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "alisik12345@mail.ru",
  "password": "123456789"
}

###

## Отправить изображение

POST http://localhost:5000/users/665485b55d3200283b14a24b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /games/dogville.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: alisik123456@mail.ru eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaXNpazEyMzQ1QG1haWwucnUiLCJ1c2VybmFtZSI6ImFsaXNpazEyMzQ1IiwiaWQiOiI2NjY2OWZkNzgzNjYzYzc1OTRkMGJmMTciLCJpYXQiOjE3MTgwMTQ0NTMsImV4cCI6MTcxODE4NzI1M30.GsIOqQuB_vLqrefsE2ieJgZHEW73K6AmOFZ8ZGOmqyk

###

## Выйти из приложения

DELETE http://localhost:5000/users/logout HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaXNpazEyMzQ1QG1haWwucnUiLCJ1c2VybmFtZSI6ImFsaXNpazEyMzQ1IiwiaWQiOiI2NjY2OWZkNzgzNjYzYzc1OTRkMGJmMTciLCJpYXQiOjE3MTgwMTQ0NTMsImV4cCI6MTcxODE4NzI1M30.GsIOqQuB_vLqrefsE2ieJgZHEW73K6AmOFZ8ZGOmqyk"
}

###
