# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keksij@yandex.ru",
  "avatar": "kaifik.jpg",
  "userName": "supercat1000",
  "password": "shining",
  "type": "обычный"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keksij@yandex.ru",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/users/665485b55d3200283b14a24b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /games/dogville.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: keksij@yandex.ru eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NpakB5YW5kZXgucnUiLCJ1c2VybmFtZSI6InN1cGVyY2F0MTAwMCIsImlkIjoiNjY1NDg1YjU1ZDMyMDAyODNiMTRhMjRiIiwiaWF0IjoxNzE3NDk3NjI5LCJleHAiOjE3MTc2NzA0Mjl9.As0iLAf1NGL4oA7XHBtIcVtQBhZZP2B0Pagxn7_8eOA

###
